#!/usr/bin/env pwsh
# ============================================================================
# Changelog Generator Module
# ============================================================================
# Generates AI-powered changelogs using Claude API and maintains historical
# changelog tracking in assets/changelog.json
# BUILD-STEP: 3
# ============================================================================

param(
    [Parameter(Mandatory=$true)]
    [string]$ProjectRoot,

    [Parameter(Mandatory=$true)]
    [string]$ReleaseDir,

    [Parameter(Mandatory=$true)]
    [string]$Version,

    [Parameter(Mandatory=$true)]
    [string]$CommitShort,

    [Parameter(Mandatory=$true)]
    [string]$CommitFull,

    [Parameter(Mandatory=$false)]
    [string]$Tag,

    [Parameter(Mandatory=$false)]
    [ValidateSet('windows', 'linux', 'macos')]
    [string]$Platform = 'windows'
)

function Get-CommitsSinceLastBuild {
    param(
        [string]$ReleaseDir,
        [string]$LastTag,
        [string]$Platform
    )

    $lastBuildFile = Join-Path $ReleaseDir ".last-build-commit-$Platform"
    $lastCommit = $null

    if (Test-Path $lastBuildFile) {
        $lastCommit = Get-Content $lastBuildFile -ErrorAction SilentlyContinue
    }

    # Get commits since last build
    $commitRange = if ($lastCommit) {
        "$lastCommit..HEAD"
    } elseif ($LastTag) {
        "$lastTag..HEAD"
    } else {
        "HEAD~10..HEAD"
    }

    $commits = @(git log $commitRange --pretty=format:"%h|%s|%an|%ar" 2>$null)

    return @{
        Commits = $commits
        Range = $commitRange
    }
}

function Invoke-ClaudeChangelogGeneration {
    param(
        [string]$ProjectRoot,
        [array]$Commits
    )

    # Load Claude API key
    $apiKey = $null
    $envPath = Join-Path $ProjectRoot ".env"
    if (Test-Path $envPath) {
        Get-Content $envPath | ForEach-Object {
            if ($_ -match '^ANTHROPIC_API_KEY=(.+)$') {
                $apiKey = $matches[1].Trim()
            }
        }
    }
    if (-not $apiKey) { $apiKey = $env:ANTHROPIC_API_KEY }

    if (-not $apiKey) {
        Write-Host "  [WARN] No Claude API key (set ANTHROPIC_API_KEY in .env)" -ForegroundColor Yellow
        return $null
    }

    Write-Host "  Calling Claude API..." -ForegroundColor Gray

    $commitList = ($Commits | ForEach-Object { "- $_" }) -join "`n"
    $prompt = @"
Analyze these git commits and create a concise, structured changelog in markdown format.

Commits (format: hash|message|author|time):
$commitList

Generate a changelog with these sections (only include sections that have changes):
### ✨ Features
### 🐛 Bug Fixes
### 🔧 Improvements
### 📝 Documentation
### 🧹 Chores

Rules:
- Be concise, use bullet points
- Group related changes
- Use imperative mood (e.g., "Add feature" not "Added feature")
- Omit commit hashes and authors
- Only include meaningful changes
- Maximum 10 items total
"@

    $body = @{
        model = "claude-sonnet-4-5-20250929"
        max_tokens = 1024
        messages = @(@{
            role = "user"
            content = $prompt
        })
    } | ConvertTo-Json -Depth 10

    try {
        $response = Invoke-RestMethod -Uri "https://api.anthropic.com/v1/messages" `
            -Method Post `
            -Headers @{
                "x-api-key" = $apiKey
                "anthropic-version" = "2023-06-01"
                "content-type" = "application/json; charset=utf-8"
            } `
            -Body $body `
            -ErrorAction Stop

        Write-Host "  [OK] Changelog generated by Claude AI" -ForegroundColor Green
        return $response.content[0].text
    } catch {
        Write-Host "  [WARN] Claude API failed: $($_.Exception.Message)" -ForegroundColor Yellow
        return $null
    }
}

function New-FallbackChangelog {
    param([array]$Commits)

    if ($Commits.Count -eq 0) {
        return "## Changes`n`nNo changes since last build."
    }

    $changelogContent = "## Changes`n`n"
    $changelogContent += ($Commits | ForEach-Object {
        $parts = $_ -split '\|'
        "- $($parts[1])"
    }) -join "`n"

    return $changelogContent
}

function Update-HistoricalChangelog {
    param(
        [string]$ProjectRoot,
        [string]$Version,
        [string]$CommitShort,
        [string]$ChangelogContent,
        [string]$Platform
    )

    $changelogFile = Join-Path $ProjectRoot "assets/changelog-$Platform.json"
    $assetsDir = Join-Path $ProjectRoot "assets"

    if (-not (Test-Path $assetsDir)) {
        New-Item -ItemType Directory -Path $assetsDir | Out-Null
    }

    $historicalChangelog = @{ releases = @() }
    if (Test-Path $changelogFile) {
        try {
            $historicalChangelog = Get-Content $changelogFile -Raw | ConvertFrom-Json
            if (-not $historicalChangelog.releases) {
                $historicalChangelog.releases = @()
            }
        } catch {
            $historicalChangelog = @{ releases = @() }
        }
    }

    # Add new release
    $newRelease = @{
        version = $Version
        date = (Get-Date -Format "yyyy-MM-ddTHH:mm:ssZ")
        changelog = $ChangelogContent
        commit = $CommitShort
    }

    $releases = @($newRelease)
    if ($historicalChangelog.releases -and $historicalChangelog.releases.Count -gt 0) {
        $releases += $historicalChangelog.releases
    }
    $historicalChangelog.releases = $releases

    # Write JSON with proper UTF-8 encoding (without BOM) to preserve emojis
    $jsonContent = $historicalChangelog | ConvertTo-Json -Depth 10
    $utf8NoBom = New-Object System.Text.UTF8Encoding $false
    [System.IO.File]::WriteAllText($changelogFile, $jsonContent, $utf8NoBom)

    Write-Host "  [OK] Updated $changelogFile" -ForegroundColor Green
}

function Save-LastBuildCommit {
    param(
        [string]$ReleaseDir,
        [string]$CommitFull,
        [string]$Platform
    )

    $lastBuildFile = Join-Path $ReleaseDir ".last-build-commit-$Platform"
    $CommitFull | Set-Content $lastBuildFile -NoNewline
}

# ============================================================================
# Main Execution
# ============================================================================

Write-Host "Generating AI-powered changelog for $Platform..." -ForegroundColor Yellow

try {
    # Get commits since last build
    $lastTag = $Tag
    $commitData = Get-CommitsSinceLastBuild -ReleaseDir $ReleaseDir -LastTag $lastTag -Platform $Platform

    if ($commitData.Commits -and $commitData.Commits.Count -gt 0) {
        Write-Host "  Analyzing $($commitData.Commits.Count) commits..." -ForegroundColor Gray

        # Try to generate changelog with Claude AI
        $changelogContent = Invoke-ClaudeChangelogGeneration -ProjectRoot $ProjectRoot -Commits $commitData.Commits

        # Fallback to simple changelog if API failed
        if (-not $changelogContent) {
            $changelogContent = New-FallbackChangelog -Commits $commitData.Commits
        }
    } else {
        Write-Host "  No new commits to analyze" -ForegroundColor DarkGray
        $changelogContent = "## Changes`n`nNo changes since last build."
    }

    # Update historical changelog
    Update-HistoricalChangelog -ProjectRoot $ProjectRoot -Version $Version -CommitShort $CommitShort -ChangelogContent $changelogContent -Platform $Platform

    # Save current commit as last build
    Save-LastBuildCommit -ReleaseDir $ReleaseDir -CommitFull $CommitFull -Platform $Platform

    Write-Host "[OK] Changelog generation complete" -ForegroundColor Green

    # Validate changelog was generated
    if (-not $changelogContent -or $changelogContent.Length -lt 10) {
        Write-Host "[ERROR] Changelog generation produced invalid content" -ForegroundColor Red
        throw "Invalid changelog content"
    }

    # Return changelog content
    return @{
        Success = $true
        ChangelogMarkdown = $changelogContent
        CommitCount = if ($commitData.Commits) { $commitData.Commits.Count } else { 0 }
    }

} catch {
    Write-Host "[ERROR] Changelog generation failed: $($_.Exception.Message)" -ForegroundColor Red
    throw "Changelog generation failed: $($_.Exception.Message)"
}
