#!/usr/bin/env pwsh
# ============================================================================
# Git Commit Module
# ============================================================================
# Commits and pushes version changes to the repository
# BUILD-STEP: 13
# ============================================================================

param(
    [Parameter(Mandatory=$true)]
    [string]$ProjectRoot,

    [Parameter(Mandatory=$true)]
    [string]$Version,

    [Parameter(Mandatory=$false)]
    [switch]$SkipPush = $false
)

function Invoke-GitCommitVersion {
    param(
        [string]$ProjectRoot,
        [string]$Version,
        [bool]$SkipPush
    )

    Write-Host "  Committing version changes..." -ForegroundColor Cyan

    Push-Location $ProjectRoot

    try {
        # Check if there are changes to commit
        $gitStatus = git status --porcelain pubspec.yaml assets/changelog.json 2>&1

        if ($gitStatus) {
            Write-Host "    Changes detected in:" -ForegroundColor Gray
            if ($gitStatus -match "pubspec.yaml") {
                Write-Host "      - pubspec.yaml" -ForegroundColor Gray
            }
            if ($gitStatus -match "changelog.json") {
                Write-Host "      - assets/changelog.json" -ForegroundColor Gray
            }

            # Stage the files
            git add pubspec.yaml assets/changelog.json 2>&1 | Out-Null

            # Create commit message
            $commitMessage = @"
chore: Bump version to $Version

Auto-generated by build script

🤖 Generated with [Claude Code](https://claude.com/claude-code)

Co-Authored-By: Claude <noreply@anthropic.com>
"@

            # Commit the changes
            git commit -m $commitMessage 2>&1 | Out-Null

            if ($LASTEXITCODE -eq 0) {
                Write-Host "    [OK] Version changes committed" -ForegroundColor Green

                if (-not $SkipPush) {
                    # Push to remote
                    Write-Host "    Pushing to remote..." -ForegroundColor Gray
                    git push 2>&1 | Out-Null

                    if ($LASTEXITCODE -eq 0) {
                        Write-Host "    [OK] Changes pushed to remote" -ForegroundColor Green
                        Pop-Location
                        return @{
                            Committed = $true
                            Pushed = $true
                        }
                    } else {
                        Write-Host "    [WARN] Failed to push to remote" -ForegroundColor Yellow
                        Pop-Location
                        return @{
                            Committed = $true
                            Pushed = $false
                        }
                    }
                } else {
                    Write-Host "    [INFO] Push skipped" -ForegroundColor Gray
                    Pop-Location
                    return @{
                        Committed = $true
                        Pushed = $false
                    }
                }
            } else {
                Write-Host "    [WARN] Failed to commit changes" -ForegroundColor Yellow
                Pop-Location
                return @{
                    Committed = $false
                    Pushed = $false
                }
            }
        } else {
            Write-Host "    No version changes to commit" -ForegroundColor Gray
            Pop-Location
            return @{
                Committed = $false
                Pushed = $false
                NoChanges = $true
            }
        }
    } catch {
        Write-Host "    [WARN] Git operation failed: $_" -ForegroundColor Yellow
        Pop-Location
        return @{
            Committed = $false
            Pushed = $false
            Error = $_.Exception.Message
        }
    }
}

# ============================================================================
# Main Execution
# ============================================================================

Write-Host "Processing git operations..." -ForegroundColor Yellow

$result = Invoke-GitCommitVersion -ProjectRoot $ProjectRoot -Version $Version -SkipPush $SkipPush

if ($result.Committed) {
    Write-Host "[OK] Git operations complete" -ForegroundColor Green
} elseif ($result.NoChanges) {
    Write-Host "[INFO] No changes to commit" -ForegroundColor Gray
} else {
    Write-Host "[WARN] Git operations incomplete" -ForegroundColor Yellow
}

return $result
