/// A glyph named by MEANING.
///
/// The question the application asks is "which idea does this mark stand for",
/// never "which glyph is it". `IconData` deliberately does not cross this
/// line: it is type-neutral but not identity-neutral, so keeping it would mean
/// the Fluent skin can never use `FluentIcons` and the macOS skin can never
/// use `CupertinoIcons`, and every skin would render Phosphor glyphs forever.
/// That is the hand-painted-lookalike failure displaced from geometry onto
/// iconography (`docs/SKIN-CONTRACT.md` conflict C3).
///
/// The GLYPH WEIGHT is a skin decision too - Phosphor Regular/Bold/Fill, a
/// Fluent filled variant, an SF Symbol weight - which is why no role carries
/// one and why selected-state weight switching moves inside the skin.
///
/// **Generated, not written.** The 151 members are one per glyph the
/// application uses today, produced by
/// `grep -rhoE 'PhosphorIcons[A-Za-z]*\.[a-zA-Z0-9_]+' lib | sed 's/.*\.//' | sort -u`
/// over `lib/` at 917 references. The names are therefore Phosphor's, and that
/// is a deliberate cost taken once: renaming 151 glyphs into a house
/// vocabulary would make the mechanical substitution at P3a a judgement pass
/// over 917 sites, and the enum's job is to be an identity the skins map from,
/// not a thesaurus. A skin that has no counterpart for a role answers with its
/// nearest neighbour and registers the substitution.
///
/// Regenerate with the command above; the count is asserted by the migration's
/// own progress bar rather than by this comment.
enum IconRole {
  arrowBendDownLeft,
  arrowBendDownRight,
  arrowBendUpLeft,
  arrowClockwise,
  arrowCounterClockwise,
  arrowDown,
  arrowLeft,
  arrowRight,
  arrowSquareOut,
  arrowUUpLeft,
  arrowUp,
  arrowsClockwise,
  arrowsCounterClockwise,
  arrowsInLineVertical,
  arrowsLeftRight,
  asterisk,
  at,
  bookOpen,
  bookmark,
  broom,
  calendar,
  caretDoubleDown,
  caretDown,
  caretLeft,
  caretRight,
  caretUp,
  chartLine,
  chatText,
  check,
  checkCircle,
  checkSquare,
  checkSquareOffset,
  circle,
  circleDashed,
  circleNotch,
  clipboard,
  clock,
  clockCountdown,
  clockCounterClockwise,
  cloud,
  cloudArrowDown,
  cloudSlash,
  code,
  codeSimple,
  copy,
  copySimple,
  cursorClick,
  desktop,
  dot,
  dotsThreeVertical,
  download,
  downloadSimple,
  eye,
  eyeSlash,
  faders,
  file,
  fileAudio,
  fileCode,
  fileCss,
  fileHtml,
  fileImage,
  fileMinus,
  filePdf,
  filePlus,
  fileText,
  fileVideo,
  fileX,
  fileZip,
  files,
  filmStrip,
  flagCheckered,
  floppyDisk,
  folder,
  folderOpen,
  folderPlus,
  folderSimple,
  funnel,
  gear,
  gitBranch,
  gitCommit,
  gitDiff,
  gitMerge,
  gitPullRequest,
  globe,
  graph,
  gridFour,
  hardDrives,
  hash,
  house,
  image,
  info,
  lightbulb,
  link,
  list,
  listBullets,
  listMagnifyingGlass,
  listNumbers,
  lock,
  magnifyingGlass,
  minus,
  minusCircle,
  minusSquare,
  moon,
  mouseSimple,
  package,
  palette,
  path,
  pencil,
  pencilSimple,
  plus,
  plusCircle,
  pulse,
  question,
  record,
  rows,
  seal,
  selection,
  signIn,
  skipForward,
  sliders,
  sortAscending,
  sortDescending,
  spinner,
  square,
  stamp,
  star,
  storefront,
  sun,
  table,
  tag,
  target,
  terminal,
  textAa,
  textAlignLeft,
  textIndent,
  textOutdent,
  textT,
  textbox,
  timer,
  trash,
  tree,
  upload,
  user,
  userCircle,
  userList,
  users,
  warning,
  warningCircle,
  warningDiamond,
  x,
  xCircle,
}
